name: oydeeedashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.5.1
  auto_route: ^8.1.3


  #network connectivity
  internet_connection_checker: ^1.0.0+1

  #network requests
  dio: ^5.3.1

 #image and svg renderer
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  super_rich_text: ^1.0.0
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.20.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0
  jiffy: ^6.3.0
  pretty_dio_logger: ^1.3.1
  sidebarx: ^0.17.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  #generators
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  hive_generator: ^2.0.0
  auto_route_generator: ^8.0.0
  flutter_gen_runner: ^5.3.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
